name: fitness_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.9.3
  pinput: ^5.0.1
  flutter_svg: ^2.2.0
  dartz: ^0.10.1
  bloc: ^9.0.0
  flutter_bloc:
  retrofit: ^4.6.0
  logger: ^2.6.0  # for logging purpose
  json_annotation: ^4.9.0
    # add injectable to your dependencies
  injectable:
  get_it:
  pretty_dio_logger: ^1.4.0
  flutter_secure_storage: ^9.2.4
  flutter_localizations:
    sdk: flutter
  intl: any

  
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  top_snackbar_flutter: ^3.3.0
  cached_network_image: ^3.4.1
  sqflite: ^2.3.0
  flutter_spinkit: ^5.2.2
  connectivity_plus: ^7.0.0
  skeletonizer: ^2.1.0+1
  mockito: ^5.4.5
  equatable: ^2.0.7
  bloc_test: ^10.0.0
  animate_do: ^4.2.0
  dots_indicator: ^4.0.1

dev_dependencies: 
  injectable_generator: ^2.6.1
  retrofit_generator: ^9.1.2
  json_serializable: ^6.9.0
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.5.0
  
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true



  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto.ttf
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit.ttf
    - family: IMFellEnglish
      fonts:
        - asset: assets/fonts/IMFellEnglish.ttf
    - family: BalooThambi2
      fonts:
        - asset: assets/fonts/BalooThambi2-Regular.ttf
