// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEav4vMDA9-cvyKIdQw2z-S5_tVC7XplM',
    appId: '1:776270498948:web:9974bfa2f0703e985406d1',
    messagingSenderId: '776270498948',
    projectId: 'fitness-18125',
    authDomain: 'fitness-18125.firebaseapp.com',
    storageBucket: 'fitness-18125.firebasestorage.app',
    measurementId: 'G-Y5EFEQLZW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVZfEofWg8q7kjbLcb4GL0yA1aOrEUXd8',
    appId: '1:776270498948:android:1dbb8d66e87004525406d1',
    messagingSenderId: '776270498948',
    projectId: 'fitness-18125',
    storageBucket: 'fitness-18125.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-VFYviLd9olS9th1jd1N4W28AwSLHbdc',
    appId: '1:776270498948:ios:66eace5b64c4a21f5406d1',
    messagingSenderId: '776270498948',
    projectId: 'fitness-18125',
    storageBucket: 'fitness-18125.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-VFYviLd9olS9th1jd1N4W28AwSLHbdc',
    appId: '1:776270498948:ios:66eace5b64c4a21f5406d1',
    messagingSenderId: '776270498948',
    projectId: 'fitness-18125',
    storageBucket: 'fitness-18125.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEav4vMDA9-cvyKIdQw2z-S5_tVC7XplM',
    appId: '1:776270498948:web:324511db95982e9c5406d1',
    messagingSenderId: '776270498948',
    projectId: 'fitness-18125',
    authDomain: 'fitness-18125.firebaseapp.com',
    storageBucket: 'fitness-18125.firebasestorage.app',
    measurementId: 'G-XNYF6BMQ6X',
  );
}